# Generated by Django 3.1.7 on 2021-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('tel', models.CharField(max_length=200, verbose_name='Телефон')),
                ('add_info', models.TextField(verbose_name='Описание')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('delivery', models.CharField(max_length=10, verbose_name='Способ доставки')),
                ('size', models.CharField(max_length=1, verbose_name='Размер')),
                ('pub_date', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
