# Generated by Django 3.1.7 on 2021-02-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='add_info',
            field=models.TextField(verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery',
            field=models.CharField(max_length=10, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name',
            field=models.CharField(max_length=200, verbose_name="І'мя"),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.CharField(max_length=1, verbose_name='Розмір'),
        ),
    ]
